substitutions:
  device_name: espmmw_rr

esphome:
  name: ${device_name}
  platformio_options:
    platform: https://github.com/tasmota/platform-espressif32.git#Tasmota/203
    platform_packages:
      - framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#2.0.3
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:

wifi:
  ap:
    ssid: ${device_name}
    password: '88888888'

captive_portal:

web_server:
  port: 80
  
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${device_name}_ip
    mac_address:
      name: ${device_name}_mac

remote_receiver:
  - id: ${device_name}_null
    pin:
      number: 10
      inverted: true
    dump: raw
  - id: ${device_name}_rr
    pin:
      number: 0
    dump: raw